### ISSUE TITLE
Can revive Lambdas in hostile team, but can revive Lambdas in Players Team | Takedown on Friendly Downed Lambda causes "Dummy" State

### ISSUE THREAD

**Issue by Aaronek10** [Emana202/Lambda-Players-MWII-Takedowns-Revive-System-Support#2]
This addon with Team System breaks function where player cant revive teammates from his team.

Bug 1:

Player is in Team A and have 3 Lambdas

Team B have 4 Lambdas

2 Team A Lambdas gets downed

Player have "Press E to Revive", Player presses E, however animation does not play, progress bar appears but after finishing, nothing happens.
Bar is stuck full on screen till E is released. Lambda still is downed.

Bug 2:

If Lambda is in Players Team, standing BEHIND Downed Friendly Lambda and using E acts like takedown, making this Lambda "Dummy", this means he lies down till being removed manualy. Other Lambdas (Friendly/Teammates and Enemies) ignore this Dummy Lambda and does nothing, just goes pass him.

**Comment by Emana202** [comment]
All these issues should be fixed in the new update.
