### ISSUE TITLE
Multiplayer Error

### ISSUE THREAD

**Issue by Aaronek10** [Emana202/Lambda-Players-MWII-Takedowns-Revive-System-Support#3]
Just little error while testing on Multiplayer:
`[lambda-players-master] ...mbda-players-mwii-takedowns-revive-system-support-main/lua/lambdaplayers/extaddon/shared/lambdaplayers_mwii_revivesystem.lua:377: attempt to call method 'AreTeammates' (a nil value)
  1. LambdaRunHook - addons/lambda-players-master/lua/lambdaplayers/autorun_includes/shared/a_hookhandling.lua:17
   2. MoveToPos - addons/lambda-players-master/lua/lambdaplayers/lambda/sv_locomotion.lua:60
    3. statefunc - addons/lambda-players-master/lua/lambdaplayers/lambda/sv_states.lua:150
     4. RunBehaviour - addons/lambda-players-master/lua/entities/npc_lambdaplayer.lua:872
      5. unknown - gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua:10`

**Comment by Emana202** [comment]
Have you updated team system to the last one?

**Comment by Aaronek10** [comment]
I think yes, i can double check

**Comment by Aaronek10** [comment]
Ok, now i updated it, now i'll check with my friend if error disappeared

**Comment by Aaronek10** [comment]
Yeah, now is good, however animation  of being downed is delayed or dont plays

**Comment by Aaronek10** [comment]
[ULib] ...mbda-players-mwii-takedowns-revive-system-support-main/lua/lambdaplayers/extaddon/shared/lambdaplayers_mwii_revivesystem.lua:50: attempt to index upvalue 'reviveEnemies' (a nil value)
    1. fn - ...mbda-players-mwii-takedowns-revive-system-support-main/lua/lambdaplayers/extaddon/shared/lambdaplayers_mwii_revivesystem.lua:50
        2. unknown - lua/ulib/shared/hook.lua:109

**Comment by Emana202** [comment]
Fixed the nil value in the update. About the animation issues, Nextbots don't handle animations really well in the multiplayer, so I can't do anything about it
